# Generated by Django 3.2.20 on 2023-07-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230716_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
    ]
