# Generated by Django 3.2.20 on 2023-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230716_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
