# Generated by Django 3.2.20 on 2023-07-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230717_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
    ]
