# Generated by Django 3.2.20 on 2023-08-25 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20230818_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.TextField()),
                ('City', models.TextField()),
                ('Hotel', models.TextField()),
                ('star', models.TextField()),
                ('Continent', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('End_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Discounted_price', models.TextField()),
            ],
        ),
    ]
